import { I18nLanguage } from '@i18n/i18n';
import { DatacenterProvider } from '@sdk-ts/controller';

export interface ObjectDeclaration {
  id: string;
  label: string;
  hash: string;
  avatar: string;

  load(payload: any): void;
}


export interface AbstractActorDeclaration extends ObjectDeclaration, DatacenterProvider {
  id: string;
  language: I18nLanguage;
  alias: string;
  label: string;
  catchphrase: string;
  avatar: string;
  banner_sm: string;
  banner_md: string;
  banner_lg: string;
  banner_xl: string;
  hash: string;
  datacenter: string;
  facebook: string;
  instagram: string;
  linkedin: string;
  twitter: string;
  youtube: string;
  follower: number;
  followed: boolean;
  favorite: boolean;
  currency: string;
  timezone: string;
  withRole: boolean;
  banner: string;
}


export const actorCurrencySymbols: any = {
  "aed": "د.إ",
  "afn": "AFN",
  "all": "ALL",
  "amd": "AMD",
  "ang": "ANG",
  "aoa": "AOA",
  "ars": "ARS",
  "aud": "$",
  "awg": "AWG",
  "azn": "AZN",
  "bam": "BAM",
  "bbd": "BBD",
  "bdt": "৳",
  "bgn": "ЛВ",
  "bhd": "BHD",
  "bif": "BIF",
  "bmd": "BMD",
  "bnd": "BND",
  "bob": "BOB",
  "brl": "R$",
  "bsd": "BSD",
  "btn": "BTN",
  "bwp": "BWP",
  "byn": "BYN",
  "bzd": "BZD",
  "cad": "$",
  "cdf": "CDF",
  "chf": "CHF",
  "clp": "$",
  "cny": "元",
  "cop": "$",
  "crc": "CRC",
  "cup": "CUP",
  "cve": "CVE",
  "czk": "KČ",
  "djf": "DJF",
  "dkk": "KR",
  "dop": "DOP",
  "dzd": "DZD",
  "egp": "EGP",
  "ern": "ERN",
  "etb": "ETB",
  "eur": "€",
  "fjd": "FJD",
  "fkp": "FKP",
  "gbp": "£",
  "gel": "₾",
  "ghs": "GHS",
  "gmd": "GMD",
  "gnf": "GNF",
  "gtq": "GTQ",
  "gyd": "GYD",
  "hkd": "HK$",
  "hnl": "HNL",
  "hrk": "KN",
  "huf": "FT",
  "idr": "RP",
  "ils": "₪",
  "inr": "₹",
  "iqd": "IQD",
  "irr": "IRR",
  "isk": "ISK",
  "jmd": "JMD",
  "jod": "JOD",
  "jpy": "¥",
  "kes": "KSH",
  "kgs": "KGS",
  "kmf": "KMF",
  "kpw": "KPW",
  "krw": "₩",
  "kwd": "KWD",
  "kyd": "KYD",
  "kzt": "KZT",
  "lak": "LAK",
  "lbp": "LBP",
  "lkr": "RS",
  "lrd": "LRD",
  "lsl": "LSL",
  "lyd": "LYD",
  "mad": ".د.م",
  "mdl": "MDL",
  "mga": "MGA",
  "mkd": "MKD",
  "mnt": "MNT",
  "mop": "MOP",
  "mru": "MRU",
  "mur": "MUR",
  "mvr": "MVR",
  "mwk": "MWK",
  "mxn": "MXN",
  "myr": "RM",
  "mzn": "MZN",
  "nad": "NAD",
  "ngn": "₦",
  "nio": "NIO",
  "nok": "KR",
  "npr": "NPR",
  "nzd": "$",
  "omr": "OMR",
  "pen": "$",
  "pgk": "PGK",
  "php": "₱",
  "pkr": "RS",
  "pln": "ZŁ",
  "pyg": "PYG",
  "qar": "QAR",
  "ron": "LEI",
  "rsd": "RSD",
  "rub": "₽",
  "rwf": "RWF",
  "sar": "SAR",
  "sbd": "SBD",
  "scr": "SCR",
  "sdg": "SDG",
  "sek": "KR",
  "sgd": "$",
  "sll": "SLL",
  "sos": "SOS",
  "srd": "SRD",
  "ssp": "SSP",
  "stn": "STN",
  "syp": "SYP",
  "szl": "SZL",
  "thb": "฿",
  "tjs": "TJS",
  "tmt": "TMT",
  "tnd": "TND",
  "top": "TOP",
  "try": "₺",
  "ttd": "TTD",
  "twd": "TWD",
  "tzs": "TZS",
  "uah": "₴",
  "ugx": "UGX",
  "usd": "$",
  "uyu": "UYU",
  "uzs": "UZS",
  "vef": "VEF",
  "vnd": "₫",
  "vuv": "VUV",
  "wst": "WST",
  "xaf": "XAF",
  "xcd": "XCD",
  "xof": "XOF",
  "xpf": "XPF",
  "yer": "YER",
  "zar": "R",
  "zmw": "ZMW",
  "zwl": "ZWL",
};
